configured_endpoints: 25
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/particle-health%2Fparticle_sdk-d544fe9bf9ba1bd40aae6c12e347edabeb8a4d2bb9136be8d88eb5940d3d9d79.yml
openapi_spec_hash: 95b06073ae5cc2c55d12da9ff9191f8a
config_hash: ed883c77b6bdb8463a8bf2c4f9f3c35f
